### ISSUE TITLE
[Enhancement] Make Curse of Midas for (cross-)bows

### ISSUE THREAD

**Issue by MelanX** [Darkhax-Minecraft/Cursed#13]
It would be cool if you could use curse of midas on bows and crossbows.
It's simply turning [this line](https://github.com/Darkhax-Minecraft/Cursed/blob/1.15.2/src/main/java/net/darkhax/cursed/CursedMod.java#L30) into this:
```java
public static final EnchantmentType TOOL = EnchantmentType.create("CURSED_TOOL", item -> EnchantmentType.DIGGER.canEnchantItem(item) || EnchantmentType.WEAPON.canEnchantItem(item) || EnchantmentType.BOW.canEnchantItem(item) || EnchantmentType.CROSSBOW.canEnchantItem(item));
```

**Comment by Darkhax** [comment]
Thanks for the suggestion. This curse was based on the legend of Midas's curse where everything he touched would turn to gold. For this reason the curse is only meant to work with melee weapons.
