### ISSUE TITLE
Port to 1.16

### ISSUE THREAD

**Issue by BlazeGamingNetwork** [Darkhax-Minecraft/Cursed#15]
Hi, just wanted to know if you intend on porting this mod to 1.16? I think this would be cool to implement on my server i am planning on starting.

Also have a curse idea

Curse of Corruption (can affect armor or tools, can infect other items in your inventory with Curse of Corruption. Curse of corruption will also slowly add other curses to items cursed with Curse of Corruption over time.

**Comment by Darkhax** [comment]
Thanks, the mod is now available for 1.16 versions.
