### ISSUE TITLE
Two bugs & config suggestion perhaps?

### ISSUE THREAD

**Issue by Jusey1** [Darkhax-Minecraft/Cursed#18]
I wanted to report two quick bugs real quick...

1st: The "Curse of Blindness" doesn't count as a curse (the text for it isn't red and it isn't counted as a curse by another mod I use in my pack).

2nd: The "Curse of Fragility" plays the armor breaking sound when it activates, which I assume is intentional but the sound being played is super loud for EVERYONE near the user. My friend had it on and I was able to hear it super loud in my own ears when I was like 40 to 50 blocks away from him. I am probably gonna just add this sound to my resource pack as a mute sound anyways but I felt like I should add it here.

Lastly: I wanted to ask if we will ever get a config file for this mod to disable specific curses? Some of the curses are pretty useless like "Curse of Ruin" or just weak in general like "Curse of Fading" so I would like to be able to disable them as these curses will not play well with other mods in some cases.

**Comment by Darkhax** [comment]
Thanks for the bug reports. Both of the issues you've mentioned have now been fixed. As for the config, as for 1.13.x+ Forge has mandated that mods can not provide configs to turn content on/off. There may be other mods or tools you can use to remove them from the enchantment table though.

**Comment by Jusey1** [comment]
That is odd since there is a lot of mods that allows you to turn their content on/off. Oh well.
