### ISSUE TITLE
Server overloading when playing this mod.

### ISSUE THREAD

**Issue by smallerYeet** [Darkhax-Minecraft/Cursed#20]
Forge: 34.1.42
Minecraft: 1.16.3
Mod Version: 4.0.2

So I have very little things to provide but when using this mod my server is overloading the second it started.
Here is my latest log:
https://cdn.discordapp.com/attachments/738562486113927218/785347513535299604/latest.log
Here is my Debug log:
https://drive.google.com/file/d/1C3fxas0jO9uvU_wz7upfTwDlyMUtEayD/view?usp=sharing
Here is my Spark-thing:
https://spark.lucko.me/#8dvhrKLaQV
[listmods.txt](https://github.com/Darkhax-Minecraft/Cursed/files/5650736/listmods.txt)

I can provide more if needed.

**Comment by Darkhax** [comment]
How have you verified that this mod is causing the issue? Your spark file would suggest this has something to do with random threads in other mods. Cursed is shown as being 0.01% of the profiled time which is well within the range of what would be expected. Only issue I can see is that your bookshelf version is outdated so the midas curse will not change drops as expected.

**Comment by smallerYeet** [comment]
Removed every mod till I found the one causing the problem.
I run the server now with every mod except this and now it works.

**Comment by smallerYeet** [comment]
But it turns out that my server is not overloaded. 
It Just has that message when it starts, even without the mod.
Sorry for the inconvenience.
