### ISSUE TITLE
Suggestion: Curse of Fafnir/Dragon's Blood

### ISSUE THREAD

**Issue by WilliamBlaze** [Darkhax-Minecraft/Cursed#21]
whether to call it "Curse of Fafnir" or "Curse of dragon's blood" i'll leave upto you but i'll get to the actual details for the curse suggestion now:

A Curse that's applied to armor Chest plates only.
Its effect: "reduces incoming damage to half a heart per hit, but attacks received from behind instantly kill the wearer, regardless of the player's health."

Its inspiration coming from the story of Siegfried who slayed a dragon, and the invulnerability gained after bathing in the dragon's blood. Not all of his body was bathed in the blood, as a portion of his back had been covered by a leaf at the time, which left Siegfried with a single weak spot- which played a part in his great and tragic demise when he was killed by his friend to put an end to a war.

in some retellings/edited versions of the original story, the nameless dragon is renamed to "Fafnir" as to draw further similarities between Siegfried's story and the story of Sigurd, a similar hero who also slayed a dragon.

**Comment by Darkhax** [comment]
This is a very interesting idea but I don't think it fits in with the general view/style of this mod. Thanks for the suggestion though.
