### ISSUE TITLE
Curse sound distance and frequency

### ISSUE THREAD

**Issue by someaddons** [Darkhax-Minecraft/Cursed#23]
The 3 curses: EnchantmentEcho ,EnchantmentFragility and EnchantmentIgnorance 
all play their sounds for very far away players, we got some mobs spawning with random enchants producing those. So the sounds are played very frequently aswell. Took a while to find out whats causing those random sounds.

On fragility curse the livingattackevent makes it quite spammy, as entities can fire it rapidly for stuff like in wall damage/drowning/fire, might want check the damagesource for a source entity. 

Not sure why they're playing so far away, but its quite regular when players walk normally on the surface and somewhere in caves below, sometimes at like 40+blocks away, there is a mob with an enchanted item equipped, making those sounds.

I think you could  probably make them player only aswell,  not seeing a lot of reason to have mobs produce the sounds all around

**Comment by Darkhax** [comment]
This should now be fixed, please test the new version and let me know how it goes.

https://www.curseforge.com/minecraft/mc-mods/cursed/files/3324068

**Comment by someaddons** [comment]
ye its fixed now, no longer randomly plays all around. Btw is it intended that the fragility curse also triggers on environmental/periodic damage? like poisons/cacti/fire all cause it atm

**Comment by Darkhax** [comment]
@someaddons This is partially intended. Some damage sources like cactus are meant to trigger armor damage events. Others like fire, drowning, and starving are meant to bypass armor damage events but do not with this enchantment. Will fix in a bit.

**Comment by Darkhax** [comment]
All of these issues should be fixed in the 7.1.3 release.

**Comment by someaddons** [comment]
nice, thanks! 💯
