### ISSUE TITLE
[1.16.5] Curses applying to Vampirism blood bottles

### ISSUE THREAD

**Issue by MarioSMB** [Darkhax-Minecraft/Cursed#27]
The blood bottles in the Vampirism mod use durability to indicate how full the bottle is. Most enchantments do not apply to them, but the curses added by this mod are listed as being accepted.
![2021-10-23_18 12 59](https://user-images.githubusercontent.com/1998392/138548514-6a088949-ed38-4272-a655-ed3dff938954.png)

**Comment by MarioSMB** [comment]
As a side note, this also seems to apply to other items with pseudo-durability, such as the Gorgon head from Ice & Fire.

**Comment by Darkhax** [comment]
This appears to be a bug with those mods as they have defined their items as being compatible with tool based enchantments. For example the vanilla enchantments Mending, Unbreaking, and Curse of Vanishing are also applicable. This should be a simple fix in their mods.

```java
    public boolean isEnchantable(ItemStack stack) {
        return false;
    }
```
