### ISSUE TITLE
curse of blindness still show wrong name

### ISSUE THREAD

**Issue by MilkissWhite** [Darkhax-Minecraft/Cursed#3]
curse of blindness still show it's description as item name.

 it can be fixed easilly.
 in language file(en-us.json), there is two name value.
  "enchantment.cursed.blindness": "Curse of Blindness",
  "enchantment.cursed.blindness": "Drastically lowers the vision of the user.",

 second "enchantment.cursed.blindness" missed ".desc".

 so editing this to 
  "enchantment.cursed.blindness.desc": "Drastically lowers the vision of the user.",
 will fix problem.

[lang.zip](https://github.com/Darkhax-Minecraft/Cursed/files/4278136/lang.zip)

here is fixed files for 2.0.1

**Comment by Darkhax** [comment]
Thanks for reporting this issue. I fixed it for French and Chinese as well.
