### ISSUE TITLE
korean language support

### ISSUE THREAD

**Issue by MilkissWhite** [Darkhax-Minecraft/Cursed#4]
I copy en-us and renamed ko-kr. I hope this is helpful.
 "Curse of Blindness" name fix is applied

[ko_kr.zip](https://github.com/Darkhax-Minecraft/Cursed/files/4278147/ko_kr.zip)

**Comment by Darkhax** [comment]
Thanks for translating. A new update will be out soon.

**Comment by MilkissWhite** [comment]
oops sorry. "귀속 저주" that I used for "Curse of Obedience" is already exist in vanilla minecraft(it used for "Curse of Binding"). I edited it another name. please use this new one.

[ko_kr.zip](https://github.com/Darkhax-Minecraft/Cursed/files/4278262/ko_kr.zip)
