### ISSUE TITLE
[Suggestion] Random Curse Chance

### ISSUE THREAD

**Issue by InQuognito** [Darkhax-Minecraft/Cursed#7]
I don't know how hard this would be, but if possible could you add a configurable chance (you could set it to 0 by default or whatever you want) for any compatible item to get a random curse (including vanilla curses)? That would be really cool. Like, every in-game day there is a (configurable) 0.15% chance for each item to get a random curse or something.

**Comment by InQuognito** [comment]
And to clarify, it would probably notify the user so it's not _too_ unfair.

**Comment by Darkhax** [comment]
Thanks for the suggestion. Unfortunately this goes well outside the scope of what this mod is intended to do so I do not plan to implement this here. This would work better as a CraftTweaker script, data pack, or stand alone mod.
