### ISSUE TITLE
Suggestion: Dullness

### ISSUE THREAD

**Issue by Fenekhu** [Darkhax-Minecraft/Cursed#9]
I was looking for a way to adjust the damage of various weapons in a modpack I'm working on and decided the easiest way was through enchants. The thing is, I just added 9 enchantments mods and not a single one of them had a way to reduce the damage of something. My request is for the opposite of sharpness, dullness.

**Comment by Darkhax** [comment]
This would be a good feature for my mod however for a modpack I would recommend using attribute modifiers. They provide access to more properties including modded ones, and allows you to define the specific values. https://minecraft.gamepedia.com/Attribute

**Comment by Darkhax** [comment]
This enchantment is now available in the 1.15.2 beta version `2.0.8` on CurseForge. This enchantment will lower the damage by the same amount Sharpness would add.
